# Generated by Django 4.1.7 on 2023-11-01 10:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="uploaded_image_expenses",
            options={"ordering": ("date_added",)},
        ),
        migrations.AddField(
            model_name="uploaded_image_expenses",
            name="date_added",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
