# Generated by Django 4.1.7 on 2023-11-01 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import expenses.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("expenses", "0002_alter_uploaded_image_expenses_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploaded_image_expenses",
            name="expense_name",
        ),
        migrations.RemoveField(
            model_name="uploaded_image_expenses",
            name="rndid",
        ),
        migrations.RemoveField(
            model_name="uploaded_image_expenses",
            name="total_amount",
        ),
        migrations.AddField(
            model_name="uploaded_image_expenses",
            name="reference_number",
            field=models.CharField(
                blank=True,
                default=expenses.models.create_rand_id,
                editable=False,
                max_length=255,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Expenses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expense_name", models.CharField(max_length=255)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("rndid", models.CharField(max_length=255)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("date_added",),
            },
        ),
    ]
