# Generated by Django 4.1.7 on 2023-11-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0004_expensescategory_expenses_category_keywords"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expenses",
            name="total_amount",
            field=models.FloatField(max_length=10),
        ),
    ]
