# Generated by Django 4.1.7 on 2023-11-17 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0005_alter_expenses_total_amount"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expenses",
            options={"ordering": ("-date_added",)},
        ),
    ]
